//! Builder API surface — `32 §9.7`.
//!
//! Per-struct fluent builders. Most builders are generated by `bon`'s
//! `#[derive(Builder)]` on the struct definition itself; a few types
//! whose canonical storage shape is nested (e.g. [`crate::Dataset`])
//! or whose YAML projection is non-uniform (e.g.
//! [`crate::SemanticModel`]) carry hand-rolled builders here.

pub mod data_kind;
mod dedup;
pub mod model;

pub use data_kind::{
    DatasetBuilder, GrainsetBuilder, JoinsetBuilder, NestedDatasetBuilder, NestedGrainsetBuilder,
    NestedJoinsetBuilder, NestedUnionsetBuilder, UnionsetBuilder,
};
pub use model::SemanticModelBuilder;
